{"tests/test_dataloader.py::test_wrong_loader_return_type_does_not_block_async_instance": {"type": "brittle", "detected_sequence": [["tests/test_dataloader_awaitable_35.py::test_await_dataloader_individual", "tests/test_dataloader_awaitable_35.py::test_await_dataloader_two", "tests/test_dataloader_awaitable_35.py::test_await_dataloader", "tests/test_dataloader_awaitable_35.py::test_await_dataloader_individual_safe_promise", "tests/test_dataloader_awaitable_35.py::test_await_dataloader_two_safe_promise", "tests/test_dataloader_awaitable_35.py::test_await_dataloader_safe_promise", "tests/test_benchmark.py::test_benchmark_promise_all_promise", "tests/test_benchmark.py::test_benchmark_promise_all", "tests/test_benchmark.py::test_benchmark_promise_creation_with_reject", "tests/test_benchmark.py::test_benchmark_promise_creation", "tests/test_benchmark.py::test_benchmark_promisify_custom_type", "tests/test_benchmark.py::test_benchmark_is_thenable_basic_type", "tests/test_benchmark.py::test_benchmark_promise_creation_with_resolve", "tests/test_benchmark.py::test_benchmark_is_thenable_custom_type", "tests/test_benchmark.py::test_benchmark_promise_resolve", "tests/test_spec.py::test_3_2_6_1", "tests/test_spec.py::test_3_2_5_1_if", "tests/test_spec.py::test_3_2_6_3_if_fulfilled", "tests/test_spec.py::test_3_2_5_2_if", "tests/test_spec.py::test_3_2_6_3_when_rejected", "tests/test_spec.py::test_3_2_6_5_pending", "tests/test_spec.py::test_3_2_6_3_when_fulfilled", "tests/test_spec.py::test_chained_promises", "tests/test_spec.py::test_3_2_2_3", "tests/test_spec.py::test_3_2_5_1_when", "tests/test_spec.py::test_3_2_6_5_rejected", "tests/test_spec.py::test_3_2_3_3", "tests/test_spec.py::test_3_2_6_2_when", "tests/test_spec.py::test_3_2_5_2_when", "tests/test_spec.py::test_3_2_1_2", "tests/test_spec.py::test_3_2_6_4_pending", "tests/test_spec.py::test_3_2_2_2", "tests/test_spec.py::test_promise_follows_indifentely", "tests/test_spec.py::test_3_2_1_1", "tests/test_spec.py::test_promise_resolved_after", "tests/test_spec.py::test_3_2_6_4_fulfilled", "tests/test_spec.py::test_3_2_6_2_if", "tests/test_spec.py::test_3_2_6_3_if_rejected", "tests/test_spec.py::test_3_2_3_2", "tests/test_spec.py::test_3_2_2_1", "tests/test_spec.py::test_3_2_3_1", "tests/test_spec.py::test_3_2_1", "tests/test_spec.py::test_promise_all_follows_indifentely", "tests/test_extra.py::test_promise_all_when_mixed_promises", "tests/test_extra.py::test_fulfilled", "tests/test_extra.py::test_promise_repr_rejected", "tests/test_extra.py::test_do_resolve_fail_on_call", "tests/test_extra.py::test_promisify_function_resolved[resolve]", "tests/test_extra.py::test_catch", "tests/test_extra.py::test_is_thenable_then_object", "tests/test_extra.py::test_then_all", "tests/test_extra.py::test_thrown_exceptions_have_stacktrace", "tests/test_extra.py::test_thrown_exceptions_preserve_stacktrace", "tests/test_extra.py::test_resolve_promise_subclass", "tests/test_extra.py::test_done", "tests/test_extra.py::test_promise_repr_pending", "tests/test_extra.py::test_rejected", "tests/test_extra.py::test_resolve_object[resolve]", "tests/test_extra.py::test_is_thenable_simple_object", "tests/test_extra.py::test_promise_loop", "tests/test_extra.py::test_dict_promise_if[for_dict0]", "tests/test_extra.py::test_resolve_future_rejected[resolve]", "tests/test_extra.py::test_promises_with_only_then", "tests/test_extra.py::test_is_thenable_future", "tests/test_extra.py::test_resolve_future_like[resolve]", "tests/test_extra.py::test_dict_promise_when[for_dict1]", "tests/test_extra.py::test_promise_all_when", "tests/test_extra.py::test_wait_if", "tests/test_extra.py::test_dict_promise_when[for_dict0]", "tests/test_extra.py::test_resolve_promise[resolve]", "tests/test_extra.py::test_promise_repr_fulfilled", "tests/test_extra.py::test_resolve_future[resolve]", "tests/test_extra.py::test_dict_promise_if[for_dict1]", "tests/test_extra.py::test_do_resolve", "tests/test_extra.py::test_promise_all_if", "tests/test_extra.py::test_exceptions", "tests/test_extra.py::test_get_if", "tests/test_extra.py::test_fulfill_self", "tests/test_extra.py::test_resolve_then_object[resolve]", "tests/test_extra.py::test_done_all", "tests/test_extra.py::test_promisify_function_rejected[resolve]", "tests/test_extra.py::test_promise_all_when_if_no_promises", "tests/test_extra.py::test_promises_promisify_still_works_but_deprecated_for_non_callables", "tests/test_extra.py::test_is_thenable_promise", "tests/test_issues.py::test_issue_33", "tests/test_issues.py::test_issue_11", "tests/test_issues.py::test_issue_75", "tests/test_issues.py::test_issue_26", "tests/test_issues.py::test_issue_9_safe", "tests/test_issues.py::test_issue_9", "tests/test_complex_threads.py::test_factorial", "tests/test_awaitable.py::test_await", "tests/test_awaitable.py::test_promise_coroutine", "tests/test_awaitable.py::test_await_time", "tests/test_promise_list.py::test_promise_lazy_promise", "tests/test_promise_list.py::test_bad_promises", "tests/test_promise_list.py::test_promise_contained_promise", "tests/test_promise_list.py::test_promise_basic", "tests/test_promise_list.py::test_promise_reject_skip_all_other_values", "tests/test_promise_list.py::test_empty_promises", "tests/test_promise_list.py::test_promise_rejected", "tests/test_promise_list.py::test_promise_mixed", "tests/test_dataloader.py::test_batches_multiple_requests_with_max_batch_sizes", "tests/test_dataloader.py::test_allows_priming_the_cache", "tests/test_dataloader.py::test_resolves_to_error_to_indicate_failure", "tests/test_dataloader.py::test_can_represent_failures_and_successes_simultaneously", "tests/test_dataloader.py::test_catches_error_if_loader_resolver_fails", "tests/test_dataloader.py::test_wrong_loader_return_type_does_not_block_async_instance"], ["tests/test_spec.py::test_3_2_6_3_if_rejected", "tests/test_spec.py::test_3_2_6_1", "tests/test_spec.py::test_3_2_5_2_when", "tests/test_spec.py::test_3_2_6_2_when", "tests/test_spec.py::test_3_2_3_1", "tests/test_spec.py::test_3_2_3_2", "tests/test_spec.py::test_3_2_6_4_fulfilled", "tests/test_spec.py::test_3_2_6_3_when_fulfilled", "tests/test_spec.py::test_3_2_6_3_when_rejected", "tests/test_spec.py::test_3_2_2_1", "tests/test_spec.py::test_3_2_3_3", "tests/test_spec.py::test_3_2_6_3_if_fulfilled", "tests/test_spec.py::test_3_2_6_5_rejected", "tests/test_spec.py::test_promise_follows_indifentely", "tests/test_spec.py::test_3_2_5_1_if", "tests/test_spec.py::test_3_2_6_4_pending", "tests/test_spec.py::test_3_2_2_3", "tests/test_spec.py::test_3_2_1_2", "tests/test_spec.py::test_chained_promises", "tests/test_spec.py::test_3_2_1", "tests/test_spec.py::test_promise_all_follows_indifentely", "tests/test_spec.py::test_3_2_1_1", "tests/test_spec.py::test_3_2_2_2", "tests/test_spec.py::test_3_2_6_2_if", "tests/test_spec.py::test_3_2_5_1_when", "tests/test_spec.py::test_3_2_6_5_pending", "tests/test_spec.py::test_3_2_5_2_if", "tests/test_spec.py::test_promise_resolved_after", "tests/test_issues.py::test_issue_9", "tests/test_issues.py::test_issue_75", "tests/test_issues.py::test_issue_26", "tests/test_issues.py::test_issue_33", "tests/test_issues.py::test_issue_9_safe", "tests/test_issues.py::test_issue_11", "tests/test_dataloader_awaitable_35.py::test_await_dataloader_safe_promise", "tests/test_dataloader_awaitable_35.py::test_await_dataloader_individual_safe_promise", "tests/test_dataloader_awaitable_35.py::test_await_dataloader_two_safe_promise", "tests/test_dataloader_awaitable_35.py::test_await_dataloader_two", "tests/test_dataloader_awaitable_35.py::test_await_dataloader_individual", "tests/test_dataloader_awaitable_35.py::test_await_dataloader", "tests/test_extra.py::test_thrown_exceptions_have_stacktrace", "tests/test_extra.py::test_dict_promise_if[for_dict0]", "tests/test_extra.py::test_fulfill_self", "tests/test_extra.py::test_promise_loop", "tests/test_extra.py::test_resolve_future_like[resolve]", "tests/test_extra.py::test_fulfilled", "tests/test_extra.py::test_then_all", "tests/test_extra.py::test_do_resolve_fail_on_call", "tests/test_extra.py::test_is_thenable_then_object", "tests/test_extra.py::test_resolve_future_rejected[resolve]", "tests/test_extra.py::test_resolve_promise[resolve]", "tests/test_extra.py::test_rejected", "tests/test_extra.py::test_exceptions", "tests/test_extra.py::test_promises_with_only_then", "tests/test_extra.py::test_promise_all_when_mixed_promises", "tests/test_extra.py::test_resolve_then_object[resolve]", "tests/test_extra.py::test_promisify_function_rejected[resolve]", "tests/test_extra.py::test_promise_all_if", "tests/test_extra.py::test_dict_promise_if[for_dict1]", "tests/test_extra.py::test_done_all", "tests/test_extra.py::test_promise_repr_rejected", "tests/test_extra.py::test_promises_promisify_still_works_but_deprecated_for_non_callables", "tests/test_extra.py::test_promisify_function_resolved[resolve]", "tests/test_extra.py::test_thrown_exceptions_preserve_stacktrace", "tests/test_extra.py::test_dict_promise_when[for_dict1]", "tests/test_extra.py::test_promise_all_when_if_no_promises", "tests/test_extra.py::test_is_thenable_future", "tests/test_extra.py::test_is_thenable_simple_object", "tests/test_extra.py::test_is_thenable_promise", "tests/test_extra.py::test_promise_repr_fulfilled", "tests/test_extra.py::test_do_resolve", "tests/test_extra.py::test_dict_promise_when[for_dict0]", "tests/test_extra.py::test_catch", "tests/test_extra.py::test_resolve_object[resolve]", "tests/test_extra.py::test_promise_repr_pending", "tests/test_extra.py::test_done", "tests/test_extra.py::test_resolve_promise_subclass", "tests/test_extra.py::test_resolve_future[resolve]", "tests/test_extra.py::test_promise_all_when", "tests/test_extra.py::test_wait_if", "tests/test_extra.py::test_get_if", "tests/test_awaitable.py::test_promise_coroutine", "tests/test_awaitable.py::test_await", "tests/test_awaitable.py::test_await_time", "tests/test_dataloader.py::test_supports_loading_multiple_keys_in_one_call", "tests/test_dataloader.py::test_coalesces_identical_requests", "tests/test_dataloader.py::test_allows_priming_the_cache", "tests/test_dataloader.py::test_caches_failed_fetches", "tests/test_dataloader.py::test_clears_all_values_in_loader", "tests/test_dataloader.py::test_wrong_loader_return_type_does_not_block_async_instance"], ["tests/test_complex_threads.py::test_factorial", "tests/test_dataloader.py::test_batches_multiple_requests", "tests/test_dataloader.py::test_allows_priming_the_cache", "tests/test_dataloader.py::test_catches_error_if_loader_resolver_fails", "tests/test_dataloader.py::test_resolves_to_error_to_indicate_failure", "tests/test_dataloader.py::test_can_call_a_loader_from_a_loader", "tests/test_dataloader.py::test_caches_failed_fetches", "tests/test_dataloader.py::test_does_not_replace_cache_map", "tests/test_dataloader.py::test_clears_all_values_in_loader", "tests/test_dataloader.py::test_does_not_prime_keys_that_already_exist", "tests/test_dataloader.py::test_batches_multiple_requests_with_max_batch_sizes", "tests/test_dataloader.py::test_dataloader_clear_with_missing_key_works", "tests/test_dataloader.py::test_supports_loading_multiple_keys_in_one_call", "tests/test_dataloader.py::test_build_a_simple_data_loader", "tests/test_dataloader.py::test_coalesces_identical_requests", "tests/test_dataloader.py::test_caches_repeated_requests", "tests/test_dataloader.py::test_can_represent_failures_and_successes_simultaneously", "tests/test_dataloader.py::test_clears_single_value_in_loader", "tests/test_dataloader.py::test_wrong_loader_return_type_does_not_block_async_instance"]]}, "time": 203.56976509094238}